FROM apache/airflow:2.7.0-python3.11

# Installer les dépendances supplémentaires
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark==4.8.0 \
    apache-airflow-providers-postgres==5.9.0 \
    pyspark==3.5.0 \
    delta-spark==3.2.0 \
    psycopg2-binary==2.9.9

# Copier les DAGs
COPY orchestration/airflow/dags /opt/airflow/dags

WORKDIR /opt/airflow
